### ISSUE TITLE
Null User/Pwd possible?

### ISSUE THREAD

**Issue by truthsword** [draganczukp/url#5]
Is it possible to run without password protection?

I tried leaving username and password fields blank as well as omitting those environmental variables. Obviously that failed.

Just curious, as my Bitwarden extension is incompatible with the login popup.

**Comment by draganczukp** [comment]
I'll add a config option for that, however you should know that it's a *very* bad idea. If there is no authentication at all then anyone can remove your links. What's worse is that they would be able to create links pointing anywhere. It might not seem like a bad idea, untill you suddenly have hundreds of links pointing to illegal content.

**Comment by draganczukp** [comment]
This is now implemented in version 1.1

It should be available in Docker hub in a few minutes. Use the tag `:1.1`, or stay on `:latest`

**Comment by truthsword** [comment]
> however you should know that it's a very bad idea ...

I run this primarily within the local LAN, so my risk is limited to other authenticated users. However, you do raise a point I overlooked. 

Is it possible that the login could be located within the loaded webUI, so that password managers could populate it?

**Comment by draganczukp** [comment]
> Is it possible that the login could be located within the loaded webUI, so that password managers could populate it?

That would require a lot of extra work and would most likely double the amount of code in the project. The current login mechanism uses features built into the browser to handle logging in, session and providing necessary headers to every request. 

I was thinking about rewriting most of the authentication mechanism, so I'll keep that in mind.
